#
#        $$$$$$\  $$\       $$$$$$$\
#       $$  __$$\ $$ |      $$  __$$\
#       $$ /  \__|$$ |  $$\ $$ |  $$ |$$\   $$\ $$$$$$$\   $$$$$$\   $$$$$$\   $$$$$$\
#       \$$$$$$\  $$ | $$  |$$$$$$$\ |$$ |  $$ |$$  __$$\ $$  __$$\ $$  __$$\ $$  __$$\
#        \____$$\ $$$$$$  / $$  __$$\ $$ |  $$ |$$ |  $$ |$$ /  $$ |$$$$$$$$ |$$$$$$$$ |
#       $$\   $$ |$$  _$$<  $$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$   ____|$$   ____|
#       \$$$$$$  |$$ | \$$\ $$$$$$$  |\$$$$$$  |$$ |  $$ |\$$$$$$$ |\$$$$$$$\ \$$$$$$$\
#        \______/ \__|  \__|\_______/  \______/ \__|  \__| \____$$ | \_______| \_______|
#                                                         $$\   $$ |
#                                                         \$$$$$$  |
#                                                          \______/
#


#The port where the server should listen to.
#This port has to be opened in your firewall if your servers are on different machines.
port: 100

#The password
password: